document.title = "DSB Tekstmining"

var lang_example = "Default translation text";
var lang_fullscreen = "Vollbild";
var lang_rawdata = "Rohdaten";
var lang_htmlembedding = "HTML Embedding";
var lang_source = "Quellenangabe";
var lang_loading = "Loading...";
var lang_projectsite = "Projektseite";
var lang_hubarea = "Hub Area";
var lang_options = "Optionen";
var lang_words = "Worte";
var lang_normify = "Normierung";
var lang_lemmafy = "Lemmatisierung";
var lang_variation = "Variation";
var lang_evaluation = "Evaluation";
var lang_frequency = "Häufigkeit";
var lang_profile = "Steckbrief";
var lang_textcorpus = "Textkorpus";
var lang_docreferences = "Dokumentreferenzen";
var lang_characters = "Zeichen";
var lang_statistics = "Statistiken";
