document.title = "DSB Tekstmining"

var lang_exampletranslationtextwithanamethathopefullywontcollide = "Default translation text";
var lang_fullscreen = "Vollbild";
var lang_rawdata = "Rohdaten";
var lang_htmlembedding = "HTML Embedding";
var lang_source = "Quellenangabe";
var lang_loading = "Loading...";
var lang_projectsite = "Projektseite";
var lang_hubarea = "Hub Area";
var lang_options = "Optionen";
var lang_words = "Worte";
var lang_word = "Wort";
var lang_normify = "Normierung";
var lang_lemmafy = "Lemmatisierung";
var lang_variation = "Variation";
var lang_evaluation = "Evaluation";
var lang_frequency = "Häufigkeit";
var lang_profile = "Steckbrief";
var lang_textcorpus = "Textkorpus";
var lang_docreferences = "Dok.-Belege";
var lang_characters = "Zeichen";
var lang_statistics = "Statistiken";
var lang_document = "Dokument";
var lang_digbibliothek = "Dig. Bibliothek";
var lang_faksimilie = "Faksimile";
var lang_ebook = "Lesemodus";
var lang_year = "Jahr";
var lang_cts = "CTS";
var lang_worddistribution = "Wortverteilung";
var lang_tokensearch = "Tokensuche</br>(untokenisiert)";
var lang_searchitem = "Suchbegriff";
var lang_example = "Beispiel";
var lang_redirect = "Sende an";
var lang_enter = "Eingabe";
var lang_interactive = "Interaktiv";
var lang_sorting = "Sortierung";
var lang_typecount = "Anzahl Wortformen";
var lang_ambigsearch = "Suche inkl Ambig";
var lang_error_docref = "Für Dokumentenbelege exakte Suche durchführen oder Datenpunkte der Timeline anklicken.";
var lang_error_token = "Für Timeline Suche durchführen oder im Häufigkeitsdiagramm anklicken.";


